name: stars_treat_sim
channels:
  - conda-forge
dependencies:
  - joblib=0.15.1
  - matplotlib=3.3.4
  - numpy=1.19.2
  - pandas=1.2.3
  - pip=24.0
  - python=3.8.19
  - scipy=1.6.1
  - simpy=4.1.1
  - pip:
    - treat-sim
  

