name: stars_treat_sim
channels:
  - conda-forge
dependencies:
  - hatch
  - joblib=1.4.2
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pandas=2.2.0
  - pip=24.0
  - python=3.10.14
  - scipy=1.13.0
  - simpy=4.1.1
  - pip:
    - treat-sim
  

